services:
  jolof-admin:
    build: .
    container_name: jolof-admin
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env.production
    networks:
      - webnet

networks:
  webnet:
    external: true
